import unittest

# Module imports
from backend.Encryption import *

class UT_Encryption(unittest.TestCase):

    """
    Key:
        A Key is generated by 2048/4096/8192 Bytes.
        Each Byte is stored in hex like this:
            byte[0] = 0x5B -> byte0: str = "5B".
        
    This "doubling" results to a string doubled the Key Length.
    We need to check if key.value a is EXACTLY double in size as the input data
    """

    def test_enc_keygen_short(self):
        k: Key = Key(KeyLength.short)
        self.assertTrue(len(k.value) == k.length.value * 2)

    def test_enc_keygen_medium(self):
        k: Key = Key(KeyLength.medium)
        self.assertTrue(len(k.value) == k.length.value * 2)

    def test_enc_keygen_long(self):
        k: Key = Key(KeyLength.long)
        self.assertTrue(len(k.value) == k.length.value * 2)


if __name__ == '__main__':
    unittest.main()